version: '2'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-server-80
    command: --default-authentication-plugin=mysql_native_password
    # working_dir: /application
    volumes:
      - ./src/mysql_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=.sweetpwd.
      - MYSQL_DATABASE=home_mngmt_studio
      - MYSQL_USER=user123
      - MYSQL_PASSWORD=zaq1@WSX
    ports:
      - "8082:3306"
  website:
    container_name: php74
    image: tut:php_img
    build:
      context: ./
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
    depends_on:
      - mysql

